/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/TimelogNew copy.vue')['default']
    CreateTimelogDialog: typeof import('./src/components/CreateTimelogDialog.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    DayBlock: typeof import('./src/components/DayBlock.vue')['default']
    GeneralSettings: typeof import('./src/components/GeneralSettings.vue')['default']
    HeaderComponent: typeof import('./src/components/HeaderComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialog: typeof import('naive-ui')['NDialog']
    NDropdowm: typeof import('naive-ui')['NDropdowm']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskComponentsBackup: typeof import('./src/components/TaskComponentsBackup.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TimelogBackground: typeof import('./src/components/TimelogBackground.vue')['default']
    TimelogBlock: typeof import('./src/components/TimelogBlock.vue')['default']
    TimelogDay: typeof import('./src/components/TimelogDay.vue')['default']
    TimelogDayHeader: typeof import('./src/components/TimelogDayHeader.vue')['default']
    TimelogDayNew: typeof import('./src/components/TimelogDayNew.vue')['default']
    TimelogEditDialog: typeof import('./src/components/TimelogEditDialog.vue')['default']
    TimelogEditDialogNew: typeof import('./src/components/TimelogEditDialogNew.vue')['default']
    TimelogJob: typeof import('./src/components/TimelogJob.vue')['default']
    TimelogNew: typeof import('./src/components/TimelogNew.vue')['default']
    'TimelogNew copy': typeof import('./src/components/TimelogNew copy.vue')['default']
    TimelogWeek: typeof import('./src/components/TimelogWeek.vue')['default']
    WeekBlock: typeof import('./src/components/WeekBlock.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
